// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwuplroicitqivdhakxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dXBscm9pY2l0cWl2ZGhha3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTM1MDksImV4cCI6MjA3Mzg2OTUwOX0.cNa1EWmaVI1MIhGl-nNvBTzyHuxkJhrN3_es8nWOWdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});