// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zujkmyfwfhjkixlymgiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1amtteWZ3Zmhqa2l4bHltZ2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjkxNDIsImV4cCI6MjA3MzY0NTE0Mn0.TOJ-3fV_fKxXlUySlA936Ayeosc6PCylZEc40-J1sHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});